IF
Global("StartEndBios","AR6200",1)
InParty("7XMONT")
!Global("MontyRomanceActive","GLOBAL",2)
Global("7XMONTBio","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("7XMONTBio","GLOBAL",1)
TextScreen("Mont1Ep")
SmallWait(1)
Continue()
END

IF
Global("StartEndBios","AR6200",1)
InParty("7XMONT")
Global("MontyRomanceActive","GLOBAL",2)
Global("7XMONTBio","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("7XMONTBio","GLOBAL",1)
TextScreen("Mont2Ep")
SmallWait(1)
Continue()
END
